# Generated by Django 3.0.5 on 2025-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0003_payment_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_donation',
            name='amount',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
