# Generated by Django 3.0.5 on 2025-03-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0004_auto_20250304_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
