# Generated by Django 3.0.5 on 2025-03-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0005_paymentdonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_donation',
        ),
    ]
