# Generated by Django 3.0.5 on 2025-03-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0006_delete_payment_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdonation',
            name='amount',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
