# Generated by Django 3.0.5 on 2025-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0008_auto_20250306_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
