# Generated by Django 3.0.5 on 2025-03-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0011_auto_20250306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
