# Generated by Django 3.0.5 on 2025-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0014_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('mobile', models.IntegerField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
