# Generated by Django 3.0.5 on 2025-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0018_auto_20250403_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('weight', models.FloatField()),
                ('chronic_disease', models.BooleanField(default=False)),
                ('chronic_details', models.TextField(blank=True, null=True)),
                ('surgery', models.BooleanField(default=False)),
                ('surgery_details', models.TextField(blank=True, null=True)),
                ('medications', models.BooleanField(default=False)),
                ('medications_details', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('organs', models.ManyToManyField(to='frontendapp.Organ')),
            ],
        ),
    ]
