# Generated by Django 3.0.5 on 2025-04-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0019_organ_organdonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ_Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('weight', models.PositiveIntegerField()),
                ('chronic_disease', models.BooleanField()),
                ('chronic_details', models.TextField(blank=True, null=True)),
                ('surgery', models.BooleanField()),
                ('surgery_details', models.TextField(blank=True, null=True)),
                ('medications', models.BooleanField()),
                ('medications_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organs', models.ManyToManyField(to='frontendapp.Organ')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganDonor',
        ),
    ]
