# Generated by Django 3.0.5 on 2025-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0020_auto_20250404_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ_donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
