# Generated by Django 5.1.6 on 2025-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('donation_type', models.CharField(choices=[('Money', 'Money'), ('Food', 'Food'), ('Clothes', 'Clothes'), ('Medical Supplies', 'Medical Supplies'), ('Others', 'Others')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
