# Generated by Django 5.1 on 2025-02-24 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_jobapplication_joblisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('Money', 'Money'), ('Clothes', 'Clothes'), ('Food', 'Food'), ('Medical Supplies', 'Medical Supplies')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
