# Generated by Django 3.0.5 on 2025-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_auto_20250302_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_type',
            field=models.CharField(choices=[('Child Education Support', 'Child Education Support'), ('Patient Treatment Assistance', 'Patient Treatment Assistance'), ('Old Age Home Support', 'Old Age Home Support'), ('Food Support for Children', 'Food Support for Children'), ('Others', 'Others')], max_length=50),
        ),
    ]
