# Generated by Django 3.0.5 on 2025-03-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_auto_20250304_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
