# Generated by Django 3.0.5 on 2025-03-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_auto_20250310_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
